// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: registry.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "hive.registry.v1";

export enum ServiceStatus {
  UNKNOWN = 0,
  HEALTHY = 1,
  UNHEALTHY = 2,
  UNRECOGNIZED = -1,
}

export interface ServiceRegistration {
  id: string;
  name: string;
  host: string;
  port: number;
  version: string;
  /** time created */
  timestamp: number;
  tags: string[];
  metadata: { [key: string]: string };
}

export interface ServiceRegistration_MetadataEntry {
  key: string;
  value: string;
}

export interface RegisterServiceRequest {
  name: string;
  host: string;
  port: number;
  version: string;
  tags: string[];
  metadata: { [key: string]: string };
}

export interface RegisterServiceRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface Empty {
}

export interface GetServiceRequest {
  name: string;
  version: string;
}

export interface ListServicesRequest {
  tags: string[];
  name?: string | undefined;
  version?: string | undefined;
}

export interface ListServicesResponse {
  services: ServiceRegistration[];
}

export interface UnregisterServiceRequest {
  id: string;
}

export interface StorageStatus {
  type: string;
  healthy: boolean;
}

export interface ServiceHealthResponse {
  status: ServiceStatus;
  timestamp: number;
  uptime: number;
  storage: StorageStatus | undefined;
}

/** Heartbeat Messages */
export interface HeartbeatRequest {
  serviceId: string;
}

export interface HeartbeatResponse {
  acknowledged: boolean;
  message: string;
  service: ServiceRegistration | undefined;
}

export const HIVE_REGISTRY_V1_PACKAGE_NAME = "hive.registry.v1";

export interface RegistryClient {
  registerService(request: RegisterServiceRequest): Observable<ServiceRegistration>;

  getService(request: GetServiceRequest): Observable<ServiceRegistration>;

  listServices(request: ListServicesRequest): Observable<ListServicesResponse>;

  unregisterService(request: UnregisterServiceRequest): Observable<ServiceRegistration>;

  healthCheck(request: Empty): Observable<ServiceHealthResponse>;

  heartbeat(request: HeartbeatRequest): Observable<HeartbeatResponse>;
}

export interface RegistryController {
  registerService(
    request: RegisterServiceRequest,
  ): Promise<ServiceRegistration> | Observable<ServiceRegistration> | ServiceRegistration;

  getService(
    request: GetServiceRequest,
  ): Promise<ServiceRegistration> | Observable<ServiceRegistration> | ServiceRegistration;

  listServices(
    request: ListServicesRequest,
  ): Promise<ListServicesResponse> | Observable<ListServicesResponse> | ListServicesResponse;

  unregisterService(
    request: UnregisterServiceRequest,
  ): Promise<ServiceRegistration> | Observable<ServiceRegistration> | ServiceRegistration;

  healthCheck(
    request: Empty,
  ): Promise<ServiceHealthResponse> | Observable<ServiceHealthResponse> | ServiceHealthResponse;

  heartbeat(request: HeartbeatRequest): Promise<HeartbeatResponse> | Observable<HeartbeatResponse> | HeartbeatResponse;
}

export function RegistryControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "registerService",
      "getService",
      "listServices",
      "unregisterService",
      "healthCheck",
      "heartbeat",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Registry", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Registry", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REGISTRY_SERVICE_NAME = "Registry";
