// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: files.model.proto

/* eslint-disable */

export const protobufPackage = "";

/** Minimal cached user info */
export interface User {
  id: string;
}

/** Minimal cached organization */
export interface Organization {
  id: string;
}

export interface File {
  id: string;
  filename: string;
  originalName: string;
  mimeType: string;
  size: string;
  hash: string;
  relatedModelId: string;
  relatedModelName: string;
  purpose: string;
  uploadedById: string;
  organizationId?: string | undefined;
  category: string;
  /** JSON as string */
  metadata?: string | undefined;
  tags: string[];
  /** JSON as string */
  uploadedBy?:
    | User
    | undefined;
  /** JSON as string */
  organization?: Organization | undefined;
  createdAt: string;
  updatedAt: string;
  lastAccessedAt?: string | undefined;
  expiresAt?: string | undefined;
  voided: boolean;
  storages: FileStorage[];
}

export interface FileStorage {
  id: string;
  fileId: string;
  provider: string;
  remoteId: string;
  storagePath: string;
  storageUrl?: string | undefined;
  createdAt: string;
  file: File | undefined;
}

export interface FileUsageScope {
  id: string;
  modelName: string;
  purpose: string;
  description?: string | undefined;
  createdAt: string;
  rules: FileUsageRule[];
}

export interface FileUsageRule {
  id: string;
  scopeId: string;
  scope: FileUsageScope | undefined;
  maxFiles: number;
  createdAt: string;
}

export const _PACKAGE_NAME = "";
