// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: files.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { File } from "./files.model";

export const protobufPackage = "";

export interface QueryFileRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  organizationId?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryFileResponse {
  data: File[];
  metadata: { [key: string]: string };
}

export interface QueryFileResponse_MetadataEntry {
  key: string;
  value: string;
}

export interface CreateFileStorage {
  provider: CreateFileStorage_StorageProviders;
  remoteId: string;
  storagePath: string;
  storageUrl: string;
}

export enum CreateFileStorage_StorageProviders {
  LOCAL = 0,
  AWS_S3 = 1,
  GOOGLE_CLOUD = 2,
  AZURE_BLOB = 3,
  CLOUDFLARE_R2 = 4,
  UNRECOGNIZED = -1,
}

export interface CreateFileRequest {
  queryBuilder: QueryBuilder | undefined;
  filename: string;
  originalName: string;
  mimeType: string;
  size: string;
  hash: string;
  relatedModelId: string;
  relatedModelName: string;
  purpose: string;
  uploadedById: string;
  organizationId?:
    | string
    | undefined;
  /** JSON as string */
  metadata?: string | undefined;
  tags: string[];
  lastAccessedAt?: string | undefined;
  expiresAt?: string | undefined;
  storages: CreateFileStorage[];
  context?: RequestContext | undefined;
}

export interface GetFileResponse {
  data: File | undefined;
  metadata: { [key: string]: string };
}

export interface GetFileResponse_MetadataEntry {
  key: string;
  value: string;
}

export const _PACKAGE_NAME = "";
