// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: files.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { FileBlob, FileMetadata } from "./files.model";

export const protobufPackage = "";

export interface QueryFileRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryFileResponse {
  data: FileMetadata[];
  /** JSON as string */
  metadata: string;
}

export interface FileBlobData {
  name: string;
  size: string;
  mimeType: string;
  filename: string;
  originalName: string;
  buffer: Uint8Array;
  fieldName: string;
}

export interface CreateFileRequest {
  queryBuilder: QueryBuilder | undefined;
  blob: FileBlobData | undefined;
  relatedModelId: string;
  relatedModelName: string;
  purpose: string;
  /** JSON as string */
  metadata?: string | undefined;
  tags: string[];
  expiresAt?: string | undefined;
  context?: RequestContext | undefined;
}

export interface GetByHashRequest {
  queryBuilder: QueryBuilder | undefined;
  context?: RequestContext | undefined;
  hash: string;
}

export interface GetFileResponse {
  data:
    | FileMetadata
    | undefined;
  /** JSON as string */
  metadata: string;
}

export interface GetBlobResponse {
  data:
    | FileBlob
    | undefined;
  /** JSON as string */
  metadata: string;
}

/** Generate signed url */
export interface GenerateUploadSignedUrlRequest {
  fileName: string;
  context?:
    | RequestContext
    | undefined;
  /** Default 3600 seconds */
  expiresIn?: number | undefined;
  mimeType: string;
  queryBuilder: QueryBuilder | undefined;
  relatedModelId: string;
  relatedModelName: string;
  purpose: string;
  tags: string[];
  size: string;
}

export interface SignedUrlData {
  signedUrl: string;
  expiresAt: string;
  mimeType: string;
  key: string;
  fileName: string;
  originalName: string;
  storageUrl: string;
}

export interface GenerateUploadSignedUrlResponse {
  data:
    | SignedUrlData
    | undefined;
  /** JSON as string */
  metadata: string;
}

export const _PACKAGE_NAME = "";
