// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: files.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { FileBlob, FileMetadata } from "./files.model";

export const protobufPackage = "";

export interface QueryFileRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryFileResponse {
  data: FileMetadata[];
  /** JSON as string */
  metadata: string;
}

export interface CreateNestedBlobRequest {
  hash: string;
  size: string;
  mimeType: string;
  remoteId: string;
  filename: string;
  storagePath: string;
  storageUrl?:
    | string
    | undefined;
  /** JSON as string */
  metadata?: string | undefined;
}

export interface CreateFileRequest {
  queryBuilder: QueryBuilder | undefined;
  blob: CreateNestedBlobRequest | undefined;
  originalName: string;
  relatedModelId: string;
  relatedModelName: string;
  purpose: string;
  /** JSON as string */
  metadata?: string | undefined;
  tags: string[];
  lastAccessedAt?: string | undefined;
  expiresAt?: string | undefined;
  context?: RequestContext | undefined;
}

export interface CreateFileFromExistingBlobRequest {
  queryBuilder: QueryBuilder | undefined;
  blobId: string;
  originalName: string;
  relatedModelId: string;
  relatedModelName: string;
  purpose: string;
  /** JSON as string */
  metadata?: string | undefined;
  tags: string[];
  lastAccessedAt?: string | undefined;
  expiresAt?: string | undefined;
  context?: RequestContext | undefined;
}

export interface GetByHashRequest {
  queryBuilder: QueryBuilder | undefined;
  context?: RequestContext | undefined;
  hash: string;
}

export interface GetFileResponse {
  data:
    | FileMetadata
    | undefined;
  /** JSON as string */
  metadata: string;
}

export interface GetBlobResponse {
  data:
    | FileBlob
    | undefined;
  /** JSON as string */
  metadata: string;
}

export const _PACKAGE_NAME = "";
