// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: file-usage.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { FileUsageRule, FileUsageScope } from "./files.model";

export const protobufPackage = "";

/** Scope */
export interface QueryFileUsageScopeRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  modelName?: string | undefined;
  purpose?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryFileUsageScopeResponse {
  data: FileUsageScope[];
  metadata: string;
}

export interface CreateFileUsageScopeRequest {
  queryBuilder: QueryBuilder | undefined;
  modelName: string;
  purpose: string;
  description?: string | undefined;
  context?: RequestContext | undefined;
}

export interface UpdateFileUsageScopeRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  modelName?: string | undefined;
  purpose?: string | undefined;
  description?: string | undefined;
  context?: RequestContext | undefined;
}

export interface GetFileUsageScopeResponse {
  data: FileUsageScope | undefined;
  metadata: string;
}

/** Rule */
export interface QueryFileUsageRuleRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  scopeId?: string | undefined;
  modelName?: string | undefined;
  purpose?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryFileUsageRuleResponse {
  data: FileUsageRule[];
  metadata: string;
}

export interface CreateFileUsageRuleRequest {
  queryBuilder: QueryBuilder | undefined;
  scopeId: string;
  maxFiles: number;
  context?: RequestContext | undefined;
}

export interface UpdateFileUsageRuleRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  scopeId?: string | undefined;
  maxFiles?: number | undefined;
  context?: RequestContext | undefined;
}

export interface GetFileUsageRuleResponse {
  data: FileUsageRule | undefined;
  metadata: string;
}

export const _PACKAGE_NAME = "";
