// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: files.service.proto

/* eslint-disable */

export const protobufPackage = "hive.files.v1";

export const HIVE_FILES_V1_PACKAGE_NAME = "hive.files.v1";
