// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: amenity.message.proto

/* eslint-disable */
import { Icon, QueryBuilder } from "./common.message";

export const protobufPackage = "";

export interface Amenity {
  id: string;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
  voided: boolean;
  createdAt: string;
  /** repeated PropertyAttribute assignedProperties = 8; // TODO: define */
  updatedAt: string;
}

export interface QueryAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  organizationId?: string | undefined;
  includeVoided?: boolean | undefined;
}

export interface QueryAmenityResponse {
  data: Amenity[];
  metadata: { [key: string]: string };
}

export interface QueryAmenityResponse_MetadataEntry {
  key: string;
  value: string;
}

export interface CreateAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
}

export interface UpdateAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  name?: string | undefined;
  icon?: Icon | undefined;
}

export interface GetAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
}

export interface GetAmenityResponse {
  data: Amenity | undefined;
  metadata: { [key: string]: string };
}

export interface GetAmenityResponse_MetadataEntry {
  key: string;
  value: string;
}

export interface DeleteAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
}

export const _PACKAGE_NAME = "";
