// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: amenity.message.proto

/* eslint-disable */
import { Icon, QueryBuilder, RequestContext } from "./common.message";
import { Amenity } from "./property.models";

export const protobufPackage = "";

export interface QueryAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  organizationId?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryAmenityResponse {
  data: Amenity[];
  metadata: string;
}

export interface CreateAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
  context?: RequestContext | undefined;
}

export interface UpdateAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  name?: string | undefined;
  icon?: Icon | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetAmenityResponse {
  data:
    | Amenity
    | undefined;
  /** JSON STRINGIFIED */
  metadata: string;
}

export interface DeleteAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

export const _PACKAGE_NAME = "";
