// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: attribute-type.message.proto

/* eslint-disable */
import { Icon, QueryBuilder } from "./common.message";
import { AttributeType } from "./property.models";

export const protobufPackage = "";

export interface QueryAttributeTypeRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  organizationId?: string | undefined;
  includeVoided?: boolean | undefined;
}

export interface QueryAttributeTypeResponse {
  data: AttributeType[];
  metadata: { [key: string]: string };
}

export interface QueryAttributeTypeResponse_MetadataEntry {
  key: string;
  value: string;
}

export interface CreateAttributeTypeRequest {
  queryBuilder: QueryBuilder | undefined;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
}

export interface UpdateAttributeTypeRequest {
  queryBuilder: QueryBuilder | undefined;
  name?: string | undefined;
  icon?: Icon | undefined;
  id: string;
}

export interface GetAttributeTypeRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
}

export interface GetAttributeTypeResponse {
  data: AttributeType | undefined;
  metadata: { [key: string]: string };
}

export interface GetAttributeTypeResponse_MetadataEntry {
  key: string;
  value: string;
}

export interface DeleteAttributeTypeRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
}

export const _PACKAGE_NAME = "";
