// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: category.message.proto

/* eslint-disable */
import { Icon, QueryBuilder } from "./common.message";

export const protobufPackage = "";

export interface Category {
  id: string;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
  voided: boolean;
  createdAt: string;
  /** repeated PropertyCategory properties = 8; // TODO: define */
  updatedAt: string;
}

export interface QueryCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  organizationId?: string | undefined;
  includeVoided?: boolean | undefined;
}

export interface QueryCategoryResponse {
  data: Category[];
  metadata: { [key: string]: string };
}

export interface QueryCategoryResponse_MetadataEntry {
  key: string;
  value: string;
}

export interface CreateCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
}

export interface UpdateCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  name?: string | undefined;
  icon?: Icon | undefined;
  id: string;
}

export interface GetCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
}

export interface GetCategoryResponse {
  data: Category | undefined;
  metadata: { [key: string]: string };
}

export interface GetCategoryResponse_MetadataEntry {
  key: string;
  value: string;
}

export interface DeleteCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
}

export const _PACKAGE_NAME = "";
