// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: category.message.proto

/* eslint-disable */
import { Icon, QueryBuilder, RequestContext } from "./common.message";
import { Category } from "./property.models";

export const protobufPackage = "";

export interface QueryCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  organizationId?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryCategoryResponse {
  data: Category[];
  metadata: string;
}

export interface CreateCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
  context?: RequestContext | undefined;
}

export interface UpdateCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  name?: string | undefined;
  icon?: Icon | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetCategoryResponse {
  data: Category | undefined;
  metadata: string;
}

export interface DeleteCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

export const _PACKAGE_NAME = "";
