// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: common.message.proto

/* eslint-disable */

export const protobufPackage = "";

export interface Empty {
}

export interface Icon {
  name: string;
  family: string;
}

export interface QueryBuilder {
  /** Pagination queries */
  page?: number | undefined;
  limit?:
    | number
    | undefined;
  /** Sord queries */
  orderBy?:
    | string
    | undefined;
  /** Custome rep queries */
  v?: string | undefined;
}

export interface GetRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
}

export interface DeleteRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
}

export const _PACKAGE_NAME = "";
