// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: property.models.proto

/* eslint-disable */
import { Icon } from "./common.message";

export const protobufPackage = "";

export interface Amenity {
  id: string;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
  assignedProperties: PropertyAmenity[];
}

export interface AttributeType {
  id: string;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
  assignedProperties: PropertyAttribute[];
}

export interface Category {
  id: string;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
  properties: PropertyCategory[];
}

export interface RelationshipType {
  id: string;
  description?: string | undefined;
  aIsToB: string;
  bIsToA: string;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
  relationships: Relationship[];
}

export interface Relationship {
  id: string;
  propertyAId: string;
  propertyBId: string;
  startDate: string;
  endDate?: string | undefined;
  typeId: string;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
  type?: RelationshipType | undefined;
  propertyA?: Property | undefined;
  propertyB?: Property | undefined;
}

export interface PropertyStatusHistory {
  id: string;
  propertyId: string;
  property?: Property | undefined;
  createdAt: string;
  updatedAt: string;
  changedBy?: string | undefined;
  reason: string;
  previousStatus: string;
  newStatus: string;
}

export interface PropertyMedia {
  id: string;
  propertyId: string;
  property?: Property | undefined;
  type: string;
  url: string;
  title?: string | undefined;
  description?: string | undefined;
  metadata: { [key: string]: string };
  order: number;
  createdAt: string;
  updatedAt: string;
  voided: boolean;
}

export interface PropertyMedia_MetadataEntry {
  key: string;
  value: string;
}

export interface PropertyAttribute {
  id: string;
  propertyId: string;
  attributeId: string;
  value: string;
  property?: Property | undefined;
  attribute?: AttributeType | undefined;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PropertyAmenity {
  id: string;
  propertyId: string;
  amenityId: string;
  property?: Property | undefined;
  amenity?: Amenity | undefined;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PropertyCategory {
  id: string;
  propertyId: string;
  categoryId: string;
  property?: Property | undefined;
  category?: Category | undefined;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Property {
  id: string;
  propertyNumber: string;
  name: string;
  organizationId: string;
  icon: Icon | undefined;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
  status: string;
  description?: string | undefined;
  thumbnail?: string | undefined;
  isVirtual: boolean;
  attributes: PropertyAttribute[];
  media: PropertyMedia[];
  amenities: PropertyAmenity[];
  categories: PropertyCategory[];
  relationshipsAsA: Relationship[];
  relationshipsAsB: Relationship[];
  addressId: string;
  address?: Address | undefined;
  organization?: Organization | undefined;
  createdBy: string;
  statusHistory: PropertyStatusHistory[];
}

export interface Address {
}

export interface Organization {
}

export const _PACKAGE_NAME = "";
