// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: property-service.proto

/* eslint-disable */

export const protobufPackage = "";

export const _PACKAGE_NAME = "";
