// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: property.message.proto

/* eslint-disable */
import { Icon, QueryBuilder } from "./common.message";

export const protobufPackage = "";

export interface Property {
  id: string;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
  voided: boolean;
  createdAt: string;
  /** repeated PropertyAttribute assignedProperties = 8; // TODO: define */
  updatedAt: string;
}

export interface QueryPropertyRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  organizationId?: string | undefined;
  includeVoided?: boolean | undefined;
}

export interface QueryPropertyResponse {
  data: Property[];
  metadata: { [key: string]: string };
}

export interface QueryPropertyResponse_MetadataEntry {
  key: string;
  value: string;
}

export interface CreatePropertyRequest {
  queryBuilder: QueryBuilder | undefined;
  name: string;
  organizationId?: string | undefined;
  icon: Icon | undefined;
}

export interface UpdatePropertyRequest {
  queryBuilder: QueryBuilder | undefined;
  name?: string | undefined;
  icon?: Icon | undefined;
}

export interface GetPropertyRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
}

export interface GetPropertyResponse {
  data: Property | undefined;
  metadata: { [key: string]: string };
}

export interface GetPropertyResponse_MetadataEntry {
  key: string;
  value: string;
}

export interface DeletePropertyRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
}

export const _PACKAGE_NAME = "";
