// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: property.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import {
  Property,
  PropertyAmenity,
  PropertyAttribute,
  PropertyCategory,
  PropertyMedia,
  PropertyStatusHistory,
  Relationship,
} from "./property.models";

export const protobufPackage = "";

export interface QueryRelationshipRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  propertyAId?: string | undefined;
  propertyBId?: string | undefined;
  typeId?: string | undefined;
  includeVoided?: boolean | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  context?: RequestContext | undefined;
}

export interface QueryRelationshipResponse {
  data: Relationship[];
  metadata: string;
}

export interface CreateRelationshipRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyAId: string;
  propertyBId: string;
  startDate: string;
  endDate?: string | undefined;
  typeId: string;
  context?: RequestContext | undefined;
}

export interface UpdateRelationshipRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyAId?: string | undefined;
  propertyBId?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  typeId?: string | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetRelationshipRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetRelationshipResponse {
  data: Relationship | undefined;
  metadata: string;
}

export interface DeleteRelationshipRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

/** Property status history */
export interface QueryPropertyStatusHistoryRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  propertyId?: string | undefined;
  changedBy?: string | undefined;
  previousStatus?: string | undefined;
  newStatus?: string | undefined;
  context?: RequestContext | undefined;
}

export interface QueryPropertyStatusHistoryResponse {
  data: PropertyStatusHistory[];
  metadata: string;
}

export interface CreatePropertyStatusHistoryRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId: string;
  changedBy?: string | undefined;
  reason: string;
  previousStatus: string;
  newStatus: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyStatusHistoryRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyStatusHistoryResponse {
  data: PropertyStatusHistory | undefined;
  metadata: string;
}

export interface DeletePropertyStatusHistoryRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

/** Property media */
export interface QueryPropertyMediaRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  propertyId?: string | undefined;
  type?: string | undefined;
  size?: number | undefined;
  mimeType?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryPropertyMediaResponse {
  data: PropertyMedia[];
  metadata: string;
}

export interface CreatePropertyMediaRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId: string;
  type: string;
  url: string;
  title?: string | undefined;
  description?:
    | string
    | undefined;
  /** size ,memeType,id,e.t.c */
  metadata: { [key: string]: string };
  order: number;
  context?: RequestContext | undefined;
}

export interface CreatePropertyMediaRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface UpdatePropertyMediaRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId?: string | undefined;
  type?: string | undefined;
  url?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  metadata: { [key: string]: string };
  order?: number | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface UpdatePropertyMediaRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface GetPropertyMediaRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyMediaResponse {
  data: PropertyMedia | undefined;
  metadata: string;
}

export interface DeletePropertyMediaRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

/** Property attribute */
export interface QueryPropertyAttributeRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  propertyId?: string | undefined;
  attributeId?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryPropertyAttributeResponse {
  data: PropertyAttribute[];
  metadata: string;
}

export interface CreatePropertyAttributeRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId: string;
  attributeId: string;
  value: string;
  context?: RequestContext | undefined;
}

export interface UpdatePropertyAttributeRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId?: string | undefined;
  attributeId?: string | undefined;
  value?: string | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyAttributeRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyAttributeResponse {
  data: PropertyAttribute | undefined;
  metadata: string;
}

export interface DeletePropertyAttributeRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

/** Property Amenity */
export interface QueryPropertyAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId?: string | undefined;
  amenityId?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryPropertyAmenityResponse {
  data: PropertyAmenity[];
  metadata: string;
}

export interface CreatePropertyAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId: string;
  amenityId: string;
  context?: RequestContext | undefined;
}

export interface UpdatePropertyAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId?: string | undefined;
  amenityId?: string | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyAmenityResponse {
  data: PropertyAmenity | undefined;
  metadata: string;
}

export interface DeletePropertyAmenityRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

/** Property category */
export interface QueryPropertyCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId?: string | undefined;
  categoryId?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryPropertyCategoryResponse {
  data: PropertyCategory[];
  metadata: string;
}

export interface CreatePropertyCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId: string;
  categoryId: string;
  context?: RequestContext | undefined;
}

export interface UpdatePropertyCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId?: string | undefined;
  categoryId?: string | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyCategoryResponse {
  data: PropertyCategory | undefined;
  metadata: string;
}

export interface DeletePropertyCategoryRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

/** Property */
export interface QueryPropertyRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  includeVoided?: boolean | undefined;
  status?: string | undefined;
  addressId?: string | undefined;
  isVirtual?: boolean | undefined;
  attributeIds: string[];
  amenityIds: string[];
  categoryIds: string[];
  context?: RequestContext | undefined;
}

export interface QueryPropertyResponse {
  data: Property[];
  metadata: string;
}

export interface CreatePropertyRequest {
  queryBuilder: QueryBuilder | undefined;
  name: string;
  organizationId: string;
  addressId: string;
  createdBy: string;
  status: string;
  description?: string | undefined;
  thumbnail?: string | undefined;
  isVirtual: boolean;
  /** json string */
  attributes: string;
  amenityIds: string[];
  categoryIds: string[];
  context?: RequestContext | undefined;
}

export interface UpdatePropertyRequest {
  queryBuilder: QueryBuilder | undefined;
  name?: string | undefined;
  organizationId?: string | undefined;
  addressId?: string | undefined;
  createdBy?: string | undefined;
  status?: string | undefined;
  description?: string | undefined;
  thumbnail?: string | undefined;
  isVirtual?:
    | boolean
    | undefined;
  /** json string */
  attributes?: string | undefined;
  amenityIds: string[];
  categoryIds: string[];
  id: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetPropertyResponse {
  data: Property | undefined;
  metadata: string;
}

export interface DeletePropertyRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

export const _PACKAGE_NAME = "";
