// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: relationship-type.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { RelationshipType } from "./property.models";

export const protobufPackage = "";

export interface QueryRelationshipTypeRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryRelationshipTypeResponse {
  data: RelationshipType[];
  metadata: string;
}

export interface CreateRelationshipTypeRequest {
  queryBuilder: QueryBuilder | undefined;
  description: string;
  aIsToB: string;
  bIsToA: string;
  context?: RequestContext | undefined;
}

export interface UpdateRelationshipTypeRequest {
  queryBuilder: QueryBuilder | undefined;
  description?: string | undefined;
  aIsToB?: string | undefined;
  bIsToA?: string | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetRelationshipTypeRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
}

export interface GetRelationshipTypeResponse {
  data: RelationshipType | undefined;
  metadata: string;
}

export interface DeleteRelationshipTypeRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

export const _PACKAGE_NAME = "";
