// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: scene.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { Scene } from "./virtual-tour.model";

export const protobufPackage = "";

export interface QuerySceneRequest {
  queryBuilder: QueryBuilder | undefined;
  tourId?: string | undefined;
  propertyId?: string | undefined;
  listingId?: string | undefined;
  context?: RequestContext | undefined;
  search?: string | undefined;
}

export interface QuerySceneResponse {
  data: Scene[];
  metadata: string;
}

export interface FileData {
  buffer: Uint8Array;
  size: number;
  originalName: string;
  fileName: string;
  memeType: string;
}

export interface CreateSceneRequest {
  queryBuilder: QueryBuilder | undefined;
  tourId: string;
  name: string;
  context?: RequestContext | undefined;
  fileBuffer: Uint8Array;
  file: FileData | undefined;
}

export interface UpdateSceneRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
  tourId?: string | undefined;
}

export interface GetSceneResponse {
  metadata: string;
  data: Scene | undefined;
}

/** Streaming file upload messages */
export interface FileUploadMetadata {
  tourId: string;
  name: string;
  originalName: string;
  mimeType: string;
  totalSize: number;
  context?: RequestContext | undefined;
  queryBuilder?: QueryBuilder | undefined;
}

export interface FileUploadChunk {
  metadata?: FileUploadMetadata | undefined;
  data?: Uint8Array | undefined;
}

export interface FileUploadResponse {
  scene?: GetSceneResponse | undefined;
  success: boolean;
  error?: string | undefined;
}

export const _PACKAGE_NAME = "";
