// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: scene.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { Scene } from "./virtual-tour.model";

export const protobufPackage = "";

export interface QuerySceneRequest {
  queryBuilder: QueryBuilder | undefined;
  tourId?: string | undefined;
  propertyId?: string | undefined;
  listingId?: string | undefined;
  context?: RequestContext | undefined;
  search?: string | undefined;
}

export interface QuerySceneResponse {
  data: Scene[];
  metadata: string;
}

export interface CreateSceneRequest {
  queryBuilder: QueryBuilder | undefined;
  tourId: string;
  name: string;
  context?: RequestContext | undefined;
}

export interface UpdateSceneRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
  tourId?: string | undefined;
}

export interface GetSceneResponse {
  metadata: string;
  data: Scene | undefined;
}

export const _PACKAGE_NAME = "";
