// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: tour.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { Tour } from "./virtual-tour.model";

export const protobufPackage = "";

export interface QueryTourRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  userId?: string | undefined;
  organizationId?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
  type?: string | undefined;
  level1?: string | undefined;
  level2?: string | undefined;
  level3?: string | undefined;
  level4?: string | undefined;
  level5?: string | undefined;
  country?: string | undefined;
  postalCode?: string | undefined;
  startDateFrom?: string | undefined;
  startDateTo?: string | undefined;
  endDateFrom?: string | undefined;
  endDateTo?: string | undefined;
  createdAtFrom?: string | undefined;
  createdAtTo?: string | undefined;
  location?: string | undefined;
}

export interface QueryTourResponse {
  data: Tour[];
  metadata: string;
}

export interface CreateTourRequest {
  queryBuilder: QueryBuilder | undefined;
  context?: RequestContext | undefined;
  propertyId?: string | undefined;
  listingId?: string | undefined;
}

export interface UpdateTourRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
  propertyId?: string | undefined;
  listingId?: string | undefined;
}

export interface GetTourResponse {
  data: Tour | undefined;
  metadata: string;
}

export const _PACKAGE_NAME = "";
