// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: tour.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { Tour } from "./virtual-tour.model";

export const protobufPackage = "";

export interface QueryTourRequest {
  queryBuilder: QueryBuilder | undefined;
  propertyId?: string | undefined;
  listingId?: string | undefined;
  context?: RequestContext | undefined;
}

export interface QueryTourResponse {
  data: Tour[];
  metadata: string;
}

export interface CreateTourRequest {
  queryBuilder: QueryBuilder | undefined;
  context?: RequestContext | undefined;
  propertyId?: string | undefined;
  listingId?: string | undefined;
}

export interface UpdateTourRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
  propertyId?: string | undefined;
  listingId?: string | undefined;
}

export interface GetTourResponse {
  data: Tour | undefined;
  metadata: string;
}

export const _PACKAGE_NAME = "";
