// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: virtual-tour.model.proto

/* eslint-disable */

export const protobufPackage = "";

export interface Tour {
  id: string;
  propertyId?: string | undefined;
  listingId?: string | undefined;
  scenes: Scene[];
  createdAt: string;
  updatedAt: string;
}

export interface Scene {
  id: string;
  tourId: string;
  tour?: Tour | undefined;
  name: string;
  tileBaseUrl: string;
  width: number;
  height: number;
  tileSize: number;
  maxLevel: number;
  /** JSON stringfied array of hotsport configs */
  hotspots: string;
  position: number;
  createdAt: string;
  updatedAt: string;
}

export const _PACKAGE_NAME = "";
