// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: address.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { Address } from "./reference.model";

export const protobufPackage = "";

export interface QueryAddressRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  modelName?: string | undefined;
  purpose?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryAddressResponse {
  data: Address[];
  metadata: string;
}

export interface CreateAddressRequest {
  queryBuilder: QueryBuilder | undefined;
  modelName: string;
  purpose: string;
  description?: string | undefined;
  context?: RequestContext | undefined;
}

export interface UpdateAddressRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  modelName?: string | undefined;
  purpose?: string | undefined;
  description?: string | undefined;
  context?: RequestContext | undefined;
}

export interface GetAddressResponse {
  data: Address | undefined;
  metadata: string;
}

export const _PACKAGE_NAME = "";
