// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: address-hierarchy.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { AddressHierarchy } from "./reference.model";

export const protobufPackage = "";

export interface QueryAddressHierarchyRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  modelName?: string | undefined;
  purpose?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface QueryAddressHierarchyResponse {
  data: AddressHierarchy[];
  metadata: string;
}

export interface GetAddressHierarchyResponse {
  data: AddressHierarchy | undefined;
  metadata: string;
}

export const _PACKAGE_NAME = "";
