// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: address.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { Address } from "./reference.model";

export const protobufPackage = "";

export interface QueryAddressRequest {
  queryBuilder: QueryBuilder | undefined;
  search?: string | undefined;
  userId?: string | undefined;
  organizationId?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
  type?: string | undefined;
  level1?: string | undefined;
  level2?: string | undefined;
  level3?: string | undefined;
  level4?: string | undefined;
  level5?: string | undefined;
  country?: string | undefined;
  postalCode?: string | undefined;
  startDateFrom?: string | undefined;
  startDateTo?: string | undefined;
  endDateFrom?: string | undefined;
  endDateTo?: string | undefined;
  createdAtFrom?: string | undefined;
  createdAtTo?: string | undefined;
  location?: string | undefined;
}

export interface QueryAddressResponse {
  data: Address[];
  metadata: string;
}

export interface CreateAddressRequest {
  queryBuilder: QueryBuilder | undefined;
  context?: RequestContext | undefined;
  isOrganizationAddress: boolean;
  type: string;
  label?: string | undefined;
  address1: string;
  address2?: string | undefined;
  landmark?: string | undefined;
  level1: string;
  level2?: string | undefined;
  level3?: string | undefined;
  level4?: string | undefined;
  level5?: string | undefined;
  cityVillage?: string | undefined;
  stateProvince?: string | undefined;
  country: string;
  postalCode?: string | undefined;
  latitude?: number | undefined;
  longitude?: number | undefined;
  plusCode?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  prefered?: boolean | undefined;
  formatted?: string | undefined;
  localeFormat: { [key: string]: string };
}

export interface CreateAddressRequest_LocaleFormatEntry {
  key: string;
  value: string;
}

export interface UpdateAddressRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  context?: RequestContext | undefined;
  type?: string | undefined;
  label?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  landmark?: string | undefined;
  level1?: string | undefined;
  level2?: string | undefined;
  level3?: string | undefined;
  level4?: string | undefined;
  level5?: string | undefined;
  cityVillage?: string | undefined;
  stateProvince?: string | undefined;
  country?: string | undefined;
  postalCode?: string | undefined;
  latitude?: number | undefined;
  longitude?: number | undefined;
  plusCode?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  prefered?: boolean | undefined;
  formatted?: string | undefined;
  localeFormat: { [key: string]: string };
}

export interface UpdateAddressRequest_LocaleFormatEntry {
  key: string;
  value: string;
}

export interface GetAddressResponse {
  data: Address | undefined;
  metadata: string;
}

export const _PACKAGE_NAME = "";
