// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: reference.model.proto

/* eslint-disable */

export const protobufPackage = "";

export interface IdentifierSequence {
  id: string;
  dataModel: string;
  lastNumber: string;
  updatedAt: string;
}

export const _PACKAGE_NAME = "";
