// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: reference.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from "./common.message";
import { IdentifierSequence } from "./reference.model";

export const protobufPackage = "";

export interface QueryIdentifierSequenceRequest {
  queryBuilder: QueryBuilder | undefined;
  dataModel?: string | undefined;
  updatedAtFrom?: string | undefined;
  updatedAtTo?: string | undefined;
  context?: RequestContext | undefined;
}

export interface QueryIdentifierSequenceResponse {
  data: IdentifierSequence[];
  metadata: string;
}

export interface CreateIdentifierSequenceRequest {
  queryBuilder: QueryBuilder | undefined;
  dataModel: string;
  prefix: string;
  width: number;
  context?: RequestContext | undefined;
}

export interface GeneratedIdentifier {
  identitySequence: IdentifierSequence | undefined;
  identifier: string;
  prefix: string;
  width: number;
}

export interface CreateIdentifierSequenceResponse {
  metadata: string;
  data: GeneratedIdentifier | undefined;
}

export interface GetIdentifierSequenceResponse {
  metadata: string;
  data: IdentifierSequence | undefined;
}

export const _PACKAGE_NAME = "";
