// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.32.0
// source: common.message.proto

/* eslint-disable */

export const protobufPackage = '';

export interface Empty {}

export interface QueryBuilder {
  /** Pagination queries */
  page?: number | undefined;
  limit?: number | undefined;
  /** Sort queries */
  orderBy?: string | undefined;
  /** Custom representation queries */
  v?: string | undefined;
}

export interface GetRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
}

export interface DeleteRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  purge?: boolean | undefined;
}

export interface RequestContext {
  userId?: string | undefined;
  organizationId?: string | undefined;
}

export interface DeleteResponse {
  success: boolean;
}

export const _PACKAGE_NAME = '';
