// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.32.0
// source: org-override.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from './common.message';
import {
  OrgTemplateOverride,
  OrgTemplateOverrideVersion,
} from './template.model';

export const protobufPackage = '';

export interface UpsertOrgOverrideRequest {
  queryBuilder: QueryBuilder | undefined;
  templateKey: string;
  organizationId: string;
  /** JSON stringified — only the slots to override */
  slots: string;
  /** JSON stringified — org-specific metadata overrides */
  metadata?: string | undefined;
  changeNote?: string | undefined;
  context?: RequestContext | undefined;
}

export interface GetOrgOverrideRequest {
  queryBuilder: QueryBuilder | undefined;
  templateKey: string;
  organizationId: string;
  context?: RequestContext | undefined;
}

export interface GetOrgOverrideResponse {
  data: OrgTemplateOverride | undefined;
  /** JSON stringified */
  metadata: string;
}

export interface DeleteOrgOverrideRequest {
  queryBuilder: QueryBuilder | undefined;
  templateKey: string;
  organizationId: string;
  purge?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface ListOrgOverridesRequest {
  queryBuilder: QueryBuilder | undefined;
  organizationId: string;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface ListOrgOverridesResponse {
  data: OrgTemplateOverride[];
  /** JSON stringified */
  metadata: string;
}

export interface ListOrgOverrideVersionsRequest {
  queryBuilder: QueryBuilder | undefined;
  overrideId: string;
  context?: RequestContext | undefined;
}

export interface ListOrgOverrideVersionsResponse {
  data: OrgTemplateOverrideVersion[];
  /** JSON stringified */
  metadata: string;
}

export interface RevertOrgOverrideRequest {
  queryBuilder: QueryBuilder | undefined;
  overrideId: string;
  /** ID of the OrgTemplateOverrideVersion to revert to */
  versionId: string;
  changeNote?: string | undefined;
  context?: RequestContext | undefined;
}

export const _PACKAGE_NAME = '';
