// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.32.0
// source: template.model.proto

/* eslint-disable */

export const protobufPackage = '';

/** Supported template rendering engines */
export enum TemplateEngine {
  HANDLEBARS = 0,
  UNRECOGNIZED = -1,
}

/**
 * System default template (organizationId = null on the DB side).
 * Org-level customizations are stored in OrgTemplateOverride.
 */
export interface Template {
  id: string;
  /** unique machine key e.g. "auth.email.verification" */
  key: string;
  /** "notification" | "prompt" | "report" | "invoice" | "document" */
  type: string;
  name: string;
  description?: string | undefined;
  engine: TemplateEngine;
  /** JSON stringified { slotName: "Handlebars string" } */
  slots: string;
  /** JSON stringified JSON Schema for required/optional slots */
  schema?: string | undefined;
  /** JSON stringified type-specific config */
  metadata?: string | undefined;
  /** increments on every update */
  version: number;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
}

/** Immutable point-in-time snapshot of a Template's content. */
export interface TemplateVersion {
  id: string;
  templateId: string;
  version: number;
  /** JSON stringified */
  slots: string;
  /** JSON stringified */
  schema?: string | undefined;
  /** JSON stringified */
  metadata?: string | undefined;
  /** userId */
  changedById?: string | undefined;
  /** optional commit-message style description */
  changeNote?: string | undefined;
  createdAt: string;
}

/**
 * Per-org slot overrides — only the slots the org changed are stored here.
 * At render time: system slots merged with these (org wins on conflict).
 */
export interface OrgTemplateOverride {
  id: string;
  templateKey: string;
  organizationId: string;
  /** JSON stringified — only overridden slots */
  slots: string;
  /** JSON stringified — org-specific metadata overrides */
  metadata?: string | undefined;
  version: number;
  voided: boolean;
  createdAt: string;
  updatedAt: string;
}

/** Immutable snapshot of an OrgTemplateOverride's content. */
export interface OrgTemplateOverrideVersion {
  id: string;
  overrideId: string;
  version: number;
  /** JSON stringified */
  slots: string;
  /** JSON stringified */
  metadata?: string | undefined;
  changedById?: string | undefined;
  changeNote?: string | undefined;
  createdAt: string;
}

export const _PACKAGE_NAME = '';
