// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.32.0
// source: template.message.proto

/* eslint-disable */
import { QueryBuilder, RequestContext } from './common.message';
import { Template, TemplateEngine, TemplateVersion } from './template.model';

export const protobufPackage = '';

export interface CreateTemplateRequest {
  queryBuilder: QueryBuilder | undefined;
  key: string;
  type: string;
  name: string;
  description?: string | undefined;
  engine?: TemplateEngine | undefined;
  /** JSON stringified { slotName: "Handlebars string" } */
  slots: string;
  /** JSON stringified JSON Schema */
  schema?: string | undefined;
  /** JSON stringified type-specific config */
  metadata?: string | undefined;
  context?: RequestContext | undefined;
}

export interface UpdateTemplateRequest {
  queryBuilder: QueryBuilder | undefined;
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  /** JSON stringified — full slots replacement */
  slots?: string | undefined;
  /** JSON stringified */
  schema?: string | undefined;
  /** JSON stringified */
  metadata?: string | undefined;
  /** commit-message style description of what changed */
  changeNote?: string | undefined;
  context?: RequestContext | undefined;
}

export interface GetTemplateResponse {
  data: Template | undefined;
  /** JSON stringified */
  metadata: string;
}

export interface ListTemplatesRequest {
  queryBuilder: QueryBuilder | undefined;
  /** filter by type */
  type?: string | undefined;
  includeVoided?: boolean | undefined;
  context?: RequestContext | undefined;
}

export interface ListTemplatesResponse {
  data: Template[];
  /** JSON stringified { totalCount, currentPage, pageSize, totalPages } */
  metadata: string;
}

export interface ListTemplateVersionsRequest {
  queryBuilder: QueryBuilder | undefined;
  templateId: string;
  context?: RequestContext | undefined;
}

export interface ListTemplateVersionsResponse {
  data: TemplateVersion[];
  /** JSON stringified */
  metadata: string;
}

export interface RevertTemplateRequest {
  queryBuilder: QueryBuilder | undefined;
  templateId: string;
  /** ID of the TemplateVersion to revert to */
  versionId: string;
  changeNote?: string | undefined;
  context?: RequestContext | undefined;
}

export interface RenderTemplateRequest {
  key: string;
  /** if set, org override slots are merged in */
  organizationId?: string | undefined;
  /** JSON stringified object passed to Handlebars at compile time */
  variables: string;
  context?: RequestContext | undefined;
}

export interface RenderTemplateResponse {
  /** { slotName: "compiled output" } */
  renderedSlots: { [key: string]: string };
  /** JSON stringified merged metadata */
  metadata: string;
}

export interface RenderTemplateResponse_RenderedSlotsEntry {
  key: string;
  value: string;
}

export const _PACKAGE_NAME = '';
