// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.32.0
// source: template.service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { DeleteRequest, DeleteResponse, GetRequest } from './common.message';
import {
  DeleteOrgOverrideRequest,
  GetOrgOverrideRequest,
  GetOrgOverrideResponse,
  ListOrgOverridesRequest,
  ListOrgOverridesResponse,
  ListOrgOverrideVersionsRequest,
  ListOrgOverrideVersionsResponse,
  RevertOrgOverrideRequest,
  UpsertOrgOverrideRequest,
} from './org-override.message';
import {
  CreateTemplateRequest,
  GetTemplateResponse,
  ListTemplatesRequest,
  ListTemplatesResponse,
  ListTemplateVersionsRequest,
  ListTemplateVersionsResponse,
  RenderTemplateRequest,
  RenderTemplateResponse,
  RevertTemplateRequest,
  UpdateTemplateRequest,
} from './template.message';

export const protobufPackage = 'hive.template.v1';

export const HIVE_TEMPLATE_V1_PACKAGE_NAME = 'hive.template.v1';

export interface TemplatesClient {
  /** ── Template CRUD ────────────────────────────────────────────────────── */

  createTemplate(
    request: CreateTemplateRequest,
  ): Observable<GetTemplateResponse>;

  getTemplate(request: GetRequest): Observable<GetTemplateResponse>;

  updateTemplate(
    request: UpdateTemplateRequest,
  ): Observable<GetTemplateResponse>;

  deleteTemplate(request: DeleteRequest): Observable<DeleteResponse>;

  listTemplates(
    request: ListTemplatesRequest,
  ): Observable<ListTemplatesResponse>;

  /** ── Version management ───────────────────────────────────────────────── */

  listTemplateVersions(
    request: ListTemplateVersionsRequest,
  ): Observable<ListTemplateVersionsResponse>;

  revertTemplate(
    request: RevertTemplateRequest,
  ): Observable<GetTemplateResponse>;

  /** ── Org overrides ────────────────────────────────────────────────────── */

  upsertOrgOverride(
    request: UpsertOrgOverrideRequest,
  ): Observable<GetOrgOverrideResponse>;

  getOrgOverride(
    request: GetOrgOverrideRequest,
  ): Observable<GetOrgOverrideResponse>;

  deleteOrgOverride(
    request: DeleteOrgOverrideRequest,
  ): Observable<DeleteResponse>;

  listOrgOverrides(
    request: ListOrgOverridesRequest,
  ): Observable<ListOrgOverridesResponse>;

  listOrgOverrideVersions(
    request: ListOrgOverrideVersionsRequest,
  ): Observable<ListOrgOverrideVersionsResponse>;

  revertOrgOverride(
    request: RevertOrgOverrideRequest,
  ): Observable<GetOrgOverrideResponse>;

  /**
   * ── Rendering ──────────────────────────────────────────────────────────
   * Primary consumer method: resolves org override → merges slots → compiles with Handlebars
   */

  renderTemplate(
    request: RenderTemplateRequest,
  ): Observable<RenderTemplateResponse>;
}

export interface TemplatesController {
  /** ── Template CRUD ────────────────────────────────────────────────────── */

  createTemplate(
    request: CreateTemplateRequest,
  ):
    | Promise<GetTemplateResponse>
    | Observable<GetTemplateResponse>
    | GetTemplateResponse;

  getTemplate(
    request: GetRequest,
  ):
    | Promise<GetTemplateResponse>
    | Observable<GetTemplateResponse>
    | GetTemplateResponse;

  updateTemplate(
    request: UpdateTemplateRequest,
  ):
    | Promise<GetTemplateResponse>
    | Observable<GetTemplateResponse>
    | GetTemplateResponse;

  deleteTemplate(
    request: DeleteRequest,
  ): Promise<DeleteResponse> | Observable<DeleteResponse> | DeleteResponse;

  listTemplates(
    request: ListTemplatesRequest,
  ):
    | Promise<ListTemplatesResponse>
    | Observable<ListTemplatesResponse>
    | ListTemplatesResponse;

  /** ── Version management ───────────────────────────────────────────────── */

  listTemplateVersions(
    request: ListTemplateVersionsRequest,
  ):
    | Promise<ListTemplateVersionsResponse>
    | Observable<ListTemplateVersionsResponse>
    | ListTemplateVersionsResponse;

  revertTemplate(
    request: RevertTemplateRequest,
  ):
    | Promise<GetTemplateResponse>
    | Observable<GetTemplateResponse>
    | GetTemplateResponse;

  /** ── Org overrides ────────────────────────────────────────────────────── */

  upsertOrgOverride(
    request: UpsertOrgOverrideRequest,
  ):
    | Promise<GetOrgOverrideResponse>
    | Observable<GetOrgOverrideResponse>
    | GetOrgOverrideResponse;

  getOrgOverride(
    request: GetOrgOverrideRequest,
  ):
    | Promise<GetOrgOverrideResponse>
    | Observable<GetOrgOverrideResponse>
    | GetOrgOverrideResponse;

  deleteOrgOverride(
    request: DeleteOrgOverrideRequest,
  ): Promise<DeleteResponse> | Observable<DeleteResponse> | DeleteResponse;

  listOrgOverrides(
    request: ListOrgOverridesRequest,
  ):
    | Promise<ListOrgOverridesResponse>
    | Observable<ListOrgOverridesResponse>
    | ListOrgOverridesResponse;

  listOrgOverrideVersions(
    request: ListOrgOverrideVersionsRequest,
  ):
    | Promise<ListOrgOverrideVersionsResponse>
    | Observable<ListOrgOverrideVersionsResponse>
    | ListOrgOverrideVersionsResponse;

  revertOrgOverride(
    request: RevertOrgOverrideRequest,
  ):
    | Promise<GetOrgOverrideResponse>
    | Observable<GetOrgOverrideResponse>
    | GetOrgOverrideResponse;

  /**
   * ── Rendering ──────────────────────────────────────────────────────────
   * Primary consumer method: resolves org override → merges slots → compiles with Handlebars
   */

  renderTemplate(
    request: RenderTemplateRequest,
  ):
    | Promise<RenderTemplateResponse>
    | Observable<RenderTemplateResponse>
    | RenderTemplateResponse;
}

export function TemplatesControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createTemplate',
      'getTemplate',
      'updateTemplate',
      'deleteTemplate',
      'listTemplates',
      'listTemplateVersions',
      'revertTemplate',
      'upsertOrgOverride',
      'getOrgOverride',
      'deleteOrgOverride',
      'listOrgOverrides',
      'listOrgOverrideVersions',
      'revertOrgOverride',
      'renderTemplate',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('Templates', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('Templates', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const TEMPLATES_SERVICE_NAME = 'Templates';
